name: "example-test"
backend: "example"

input [
    {
      name: "prompt"
#     data_type: TYPE_STRING
      data_type: TYPE_FP32
      dims: [ -1 ]
    }
]

output [
    {
      name: "output"
#     data_type: TYPE_STRING
      data_type: TYPE_FP32
      dims: [ -1 ]
    }
]
